version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: expense_backend
    container_name : expense_backend
    depends_on:
      - mongodb
    ports:
      - 9000:9000
    environment:
      MONGO_URL: mongodb://mongodb:27017
      PORT: 9000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: expense_frontend
    container_name: expense_client
    depends_on:
      - server
    ports:
      - 3000:3000
volumes:
  mongodb_data: